import { useCallback, useEffect, useMemo, useState, type ChangeEvent, type FormEvent } from 'react';
import { BarChart3, Check, Download, Film, Play, Plus, Settings2, Square, Upload, X } from 'lucide-react';
import type { EvaluationCase, EvaluationCategory, EvaluationFixture, EvaluationResult, EvaluationRun, EvaluationRunSummary } from './evaluationTypes';
import { WorkflowTrace } from './WorkflowTrace';
import { MAX_MEDIA_UPLOAD_BYTES } from './uploadLimits';
import './evaluations.css';

const categoryNames: Record<EvaluationCategory, string> = { 'hot-news': '热点新闻', knowledge: '知识科普', 'multi-video': '多素材剪辑' };
const apiPath = (url: string) => `${import.meta.env.BASE_URL.replace(/\/$/, '')}${url}`;
async function api<T>(url: string, token: string, init?: RequestInit): Promise<T> {
  const response = await fetch(apiPath(`/api/admin/evaluations${url}`), { ...init, headers: { Authorization: `Bearer ${token}`, ...(init?.body && !(init.body instanceof FormData) ? { 'Content-Type': 'application/json' } : {}) } });
  const body = await response.json() as T & { error?: string };
  if (!response.ok) throw new Error(body.error || '评测请求失败。');
  return body;
}
async function media(url: string, token: string) {
  const response = await fetch(apiPath(`/api/admin/evaluations${url}`), { headers: { Authorization: `Bearer ${token}` } });
  if (!response.ok) throw new Error('评测文件暂时无法读取。');
  return URL.createObjectURL(await response.blob());
}
const blankCase = (): EvaluationCase => ({ id: '', name: '', category: 'knowledge', description: '', messages: [''], fixtureIds: [], expectation: { seconds: 45, toleranceSeconds: 3.6, format: '16:9', captions: true, html: true, minSources: 0, originalOnly: false, requiredWords: [] }, threshold: 80, enabled: true, version: 1, updatedAt: '' });
const statusName = (result: EvaluationResult) => ({ queued: '等待执行', running: '执行中', passed: '通过', failed: result.artifact ? '需要复核' : '执行失败', cancelled: '已停止', interrupted: '已中断' })[result.status];
const runStatusName = (status: EvaluationRun['status']) => ({ running: '执行中', stopping: '正在停止', completed: '已完成', cancelled: '已停止', interrupted: '已中断' })[status];

function CaseEditor({ test, fixtures, close, save }: { test: EvaluationCase; fixtures: EvaluationFixture[]; close: () => void; save: (test: EvaluationCase) => Promise<void> }) {
  const [form, setForm] = useState(() => structuredClone(test)), [words, setWords] = useState(test.expectation.requiredWords.join('，')), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const change = (patch: Partial<EvaluationCase>) => setForm(current => ({ ...current, ...patch }));
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { await save({ ...form, expectation: { ...form.expectation, requiredWords: words.split(/[,，]/).map(w => w.trim()).filter(Boolean) } }); close(); } catch (error) { setError(error instanceof Error ? error.message : '用例保存失败。'); } finally { setBusy(false); } }
  return <div className="eval-overlay"><section className="eval-dialog admin-panel" role="dialog" aria-modal="true" aria-label="配置评测用例">
    <div className="admin-panel-heading"><h2>{test.id ? '配置评测用例' : '新增评测用例'}</h2><button type="button" onClick={close} aria-label="关闭用例配置"><X size={20}/></button></div>
    <form onSubmit={event => void submit(event)}>
      <div className="admin-form-grid">
        <label>用例名称<input required value={form.name} onChange={e => change({ name: e.target.value })}/></label>
        <label>任务类型<select value={form.category} onChange={e => { const category = e.target.value as EvaluationCategory; change({ category, expectation: { ...form.expectation, minSources: category === 'multi-video' ? 2 : 0, html: category !== 'multi-video', originalOnly: category === 'multi-video' } }); }}><option value="hot-news">热点新闻</option><option value="knowledge">知识科普</option><option value="multi-video">多素材剪辑</option></select></label>
        <label className="admin-wide">考察能力<input value={form.description} onChange={e => change({ description: e.target.value })}/></label>
        {form.messages.map((message, index) => <label className="admin-wide" key={index}>第{index + 1}轮指令<textarea required rows={3} maxLength={2000} value={message} onChange={e => change({ messages: form.messages.map((m,i) => i === index ? e.target.value : m) })}/></label>)}
        <div className="eval-inline admin-wide"><button type="button" className="eval-secondary" disabled={form.messages.length >= 6} onClick={() => change({ messages: [...form.messages, ''] })}>增加后续指令</button>{form.messages.length > 1 ? <button type="button" className="eval-secondary" onClick={() => change({ messages: form.messages.slice(0,-1) })}>移除最后一轮</button> : null}</div>
        <label>最终时长（秒）<input type="number" min={10} max={form.category === 'multi-video' ? 60 : 600} value={form.expectation.seconds} onChange={e => change({ expectation: { ...form.expectation, seconds: +e.target.value, toleranceSeconds: Math.max(2, +e.target.value * .08) } })}/></label>
        <label>时长容差（秒）<input type="number" step="0.1" min="0.5" value={form.expectation.toleranceSeconds} onChange={e => change({ expectation: { ...form.expectation, toleranceSeconds: +e.target.value } })}/></label>
        <label>最终画幅<select value={form.expectation.format} onChange={e => change({ expectation: { ...form.expectation, format: e.target.value as EvaluationCase['expectation']['format'] } })}><option>16:9</option><option>9:16</option><option>1:1</option></select></label>
        <label>通过分数<input type="number" min={60} max={100} value={form.threshold} onChange={e => change({ threshold: +e.target.value })}/></label>
        <label className="admin-wide">必须说到的关键词（用逗号分隔）<input value={words} onChange={e => setWords(e.target.value)}/></label>
        <div className="eval-toggles admin-wide">{(['captions','html','originalOnly'] as const).map(key => <label key={key}><input type="checkbox" checked={form.expectation[key]} onChange={e => change({ expectation: { ...form.expectation, [key]: e.target.checked } })}/>{{ captions: '要求字幕', html: '要求HTML图解', originalOnly: '仅保留原声' }[key]}</label>)}<label><input type="checkbox" checked={form.enabled} onChange={e => change({ enabled: e.target.checked })}/>启用用例</label></div>
        <label>最少上传素材数<input type="number" min={form.category === 'multi-video' ? 2 : 0} max={6} value={form.expectation.minSources} onChange={e => change({ expectation: { ...form.expectation, minSources: +e.target.value } })}/></label>
      </div>
      <fieldset className="eval-fixture-binding"><legend>绑定评测素材 · 已选{form.fixtureIds.length}/6</legend>{fixtures.length ? fixtures.map(f => <label key={f.id}><input type="checkbox" checked={form.fixtureIds.includes(f.id)} disabled={!form.fixtureIds.includes(f.id) && form.fixtureIds.length >= 6} onChange={e => change({ fixtureIds: e.target.checked ? [...form.fixtureIds, f.id] : form.fixtureIds.filter(id => id !== f.id) })}/><span>{f.name}<small>{f.duration.toFixed(1)}秒 · {(f.bytes/1024/1024).toFixed(1)} MB</small></span></label>) : <p>先在评测集上传视频，再为本例绑定素材。</p>}</fieldset>
      {error ? <p className="admin-alert" role="alert">{error}</p> : null}
      <button className="admin-save" disabled={busy} type="submit">{busy ? '保存中…' : '保存用例'}</button>
    </form>
  </section></div>;
}

function ResultDetail({ result, runId, token, refresh }: { result: EvaluationResult; runId: string; token: string; refresh: () => Promise<void> }) {
  const [video, setVideo] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false), [score, setScore] = useState(result.humanReview?.score ?? 80), [note, setNote] = useState(result.humanReview?.note || '');
  const reviewFailures = result.artifact?.review?.checks.filter(check => !check.passed) || [];
  useEffect(() => () => { if (video) URL.revokeObjectURL(video); }, [video]);
  async function preview() { setBusy(true); setError(''); try { setVideo(await media(`/runs/${runId}/results/${result.id}/video`, token)); } catch (error) { setError(error instanceof Error ? error.message : '视频加载失败。'); } finally { setBusy(false); } }
  async function review(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { await api(`/runs/${runId}/results/${result.id}/human-review`, token, { method: 'PUT', body: JSON.stringify({ score, note }) }); await refresh(); } catch (error) { setError(error instanceof Error ? error.message : '审阅保存失败。'); } finally { setBusy(false); } }
  return <section className="admin-panel eval-result-detail">
    <div className="admin-panel-heading"><h2>{result.case.name}</h2><span>{statusName(result)} · {result.score === undefined ? '未评分' : `${result.score}/100`}</span></div>
    {result.error ? <p className="admin-alert">{result.error}</p> : null}
    <p className="eval-muted">第{result.repeat}次 · 用例v{result.case.version} · 耗时{((result.elapsedMs || 0)/1000).toFixed(1)}秒（含排队）{result.artifact ? ` · 实测${result.artifact.actualDuration.toFixed(2)}秒 · ${result.artifact.format}` : ''}</p>
    <details><summary>本次原始指令</summary><ol>{result.case.messages.map((m,i) => <li key={i}>{m}</li>)}</ol></details>
    {result.artifact ? <div className="eval-preview">{video ? <><video src={video} controls preload="metadata"/><a className="eval-secondary" href={video} download={`${result.case.name}.mp4`}><Download size={15}/>下载成片</a></> : <button className="eval-secondary" disabled={busy} onClick={() => void preview()}><Play size={15}/>{busy ? '加载中…' : '播放成片'}</button>}<small>SHA-256：{result.artifact.sha256}</small></div> : null}
    {result.checks ? <div className="eval-checks">{result.checks.map(c => <article key={c.id} className={c.passed ? 'passed' : 'failed'}><strong>{c.passed ? '✓' : '△'} {c.name}<span>{c.passed ? c.weight : 0}/{c.weight}</span></strong><p>{c.detail}</p></article>)}</div> : null}
    {reviewFailures.length ? <details className="eval-review-findings" open><summary>成片审查发现的问题 · {reviewFailures.length}项</summary><ul>{reviewFailures.map((check,index) => <li key={`${check.name}-${index}`}><strong>{check.name}</strong><p>{check.detail}</p></li>)}</ul></details> : null}
    {result.spokenText ? <details><summary>实际选中音频转写</summary><p className="eval-spoken">{result.spokenText}</p></details> : null}
    <WorkflowTrace events={result.workflow}/>
    {result.artifact ? <form className="eval-human-review" onSubmit={event => void review(event)}><h3>人工审阅</h3><p>独立记录人工分数和意见，保留原自动评分与失败项。</p><label>人工分数<input type="number" min={0} max={100} value={score} onChange={e => setScore(+e.target.value)}/></label><label>审阅意见<textarea rows={3} maxLength={3000} value={note} onChange={e => setNote(e.target.value)} placeholder="画面、叙事、节奏或声音中仍需改进的地方"/></label><button className="eval-secondary" type="submit" disabled={busy}>保存人工审阅</button>{result.humanReview ? <small>上次保存：{new Date(result.humanReview.reviewedAt).toLocaleString('zh-CN')}</small> : null}</form> : null}
    {error ? <p className="admin-alert" role="alert">{error}</p> : null}
  </section>;
}

export default function EvaluationAdmin({ token, models }: { token: string; models: Array<{ id: string; name: string; kind: string; enabled: boolean; hasApiKey: boolean }> }) {
  const [cases, setCases] = useState<EvaluationCase[]>([]), [fixtures, setFixtures] = useState<EvaluationFixture[]>([]), [runs, setRuns] = useState<EvaluationRunSummary[]>([]);
  const [selected, setSelected] = useState<string[]>([]), [category, setCategory] = useState<EvaluationCategory | 'all'>('all'), [editor, setEditor] = useState<EvaluationCase | null>(null);
  const [pane, setPane] = useState<'cases' | 'runs'>('cases'), [runId, setRunId] = useState(''), [run, setRun] = useState<EvaluationRun | null>(null), [resultId, setResultId] = useState('');
  const [modelId, setModelId] = useState(''), [name, setName] = useState(''), [repeats, setRepeats] = useState(1), [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const [baselineId, setBaselineId] = useState(''), [baseline, setBaseline] = useState<EvaluationRun | null>(null);
  const refresh = useCallback(async (signal?: AbortSignal) => {
    const [catalog, history, detail] = await Promise.all([api<{ cases: EvaluationCase[]; fixtures: EvaluationFixture[] }>('/cases', token, { signal }), api<{ runs: EvaluationRunSummary[] }>('/runs', token, { signal }), runId ? api<{ run: EvaluationRun }>(`/runs/${runId}`, token, { signal }) : Promise.resolve(null)]);
    setCases(catalog.cases); setFixtures(catalog.fixtures); setRuns(history.runs); if (detail) setRun(detail.run);
  }, [token, runId]);
  useEffect(() => { const controller = new AbortController(); void refresh(controller.signal).catch(error => { if (!controller.signal.aborted) setError(error instanceof Error ? error.message : '评测加载失败。'); }); return () => controller.abort(); }, [refresh]);
  const active = runs.some(r => r.status === 'running' || r.status === 'stopping');
  useEffect(() => { if (!active) return; const controller = new AbortController(); let timer: ReturnType<typeof setTimeout>; const poll = async () => { try { await refresh(controller.signal); } catch (error) { if (!controller.signal.aborted) setError(error instanceof Error ? error.message : '无法读取评测进度。'); } if (!controller.signal.aborted) timer = setTimeout(() => void poll(), 2000); }; timer = setTimeout(() => void poll(), 2000); return () => { controller.abort(); clearTimeout(timer); }; }, [active, refresh]);
  useEffect(() => { if (!baselineId) { setBaseline(null); return; } const controller = new AbortController(); void api<{ run: EvaluationRun }>(`/runs/${baselineId}`, token, { signal: controller.signal }).then(data => setBaseline(data.run)).catch(error => { if (!controller.signal.aborted) setError(error instanceof Error ? error.message : '对比记录加载失败。'); }); return () => controller.abort(); }, [baselineId, token]);
  const visibleCases = cases.filter(c => category === 'all' || c.category === category), selectedCases = cases.filter(c => selected.includes(c.id));
  const missing = selectedCases.find(c => c.fixtureIds.length < c.expectation.minSources), summary = runs.find(r => r.id === runId)?.summary;
  const result = run?.results.find(r => r.id === resultId);
  const baselineScores = useMemo(() => { const result = new Map<string, number[]>(); if (baseline?.snapshot.rubricVersion !== run?.snapshot.rubricVersion) return result; for (const r of baseline?.results || []) if (r.score !== undefined) result.set(r.caseHash, [...(result.get(r.caseHash) || []), r.score]); return result; }, [baseline, run?.snapshot.rubricVersion]);
  async function save(test: EvaluationCase) { const result = await api<{ case: EvaluationCase }>(test.id ? `/cases/${test.id}` : '/cases', token, { method: test.id ? 'PUT' : 'POST', body: JSON.stringify(test) }); setCases(current => test.id ? current.map(c => c.id === test.id ? result.case : c) : [...current, result.case]); if (!result.case.enabled) setSelected(current => current.filter(id => id !== result.case.id)); setNotice('用例已保存；历史评测保留原版本。'); }
  async function start() { setBusy(true); setError(''); setNotice(''); try { const data = await api<{ run: EvaluationRun }>('/runs', token, { method: 'POST', body: JSON.stringify({ caseIds: selected, repeats, modelId: modelId || undefined, name: name || undefined }) }); setRun(data.run); setRunId(data.run.id); setResultId(''); setPane('runs'); } catch (error) { setError(error instanceof Error ? error.message : '评测启动失败。'); } finally { setBusy(false); } }
  async function stop() { if (!run) return; setBusy(true); setError(''); try { const data = await api<{ run: EvaluationRun }>(`/runs/${run.id}/stop`, token, { method: 'POST' }); setRun(data.run); await refresh(); } catch (error) { setError(error instanceof Error ? error.message : '停止失败。'); } finally { setBusy(false); } }
  async function upload(event: ChangeEvent<HTMLInputElement>) { const files = Array.from(event.target.files || []); event.target.value = ''; if (!files.length) return; if (files.some(f => !f.type.startsWith('video/') || f.size > MAX_MEDIA_UPLOAD_BYTES)) { setError('仅支持每段100 MB以内的视频。'); return; } setBusy(true); setError(''); let added = 0; try { for (const file of files.slice(0,6)) { const body = new FormData(); body.append('file', file); const data = await api<{ fixture: EvaluationFixture }>('/fixtures', token, { method: 'POST', body }); setFixtures(current => [...current, data.fixture]); added++; } setNotice(`已上传${added}段评测视频，可在“配置用例”中绑定。`); } catch (error) { setError(`${added ? `已保留${added}段成功素材。` : ''}${error instanceof Error ? error.message : '上传失败。'}`); } finally { setBusy(false); } }
  async function downloadReport() { if (!run) return; setError(''); try { const url = await media(`/runs/${run.id}/report`, token); const a = document.createElement('a'); a.href = url; a.download = `qingjian-evaluation-${run.id}.json`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); } catch (error) { setError(error instanceof Error ? error.message : '导出失败。'); } }
  return <div className="evaluation-admin">
    <div className="admin-heading"><div><h1>Agent 能力评测</h1><p>用真实成片检验新闻解读、知识讲解与多素材剪辑，持续比较改进。</p></div><BarChart3 size={28}/></div>
    {error ? <div className="admin-alert" role="alert">{error}<button aria-label="关闭评测错误" onClick={() => setError('')}><X size={16}/></button></div> : null}
    {notice ? <div className="admin-notice" role="status"><Check size={16}/>{notice}</div> : null}
    <div className="eval-nav"><button className={pane === 'cases' ? 'active' : ''} onClick={() => setPane('cases')}>评测集 <span>{cases.length}</span></button><button className={pane === 'runs' ? 'active' : ''} onClick={() => setPane('runs')}>评测历史 <span>{runs.length}</span></button></div>
    {pane === 'cases' ? <>
      <section className="admin-panel eval-launch"><div className="admin-panel-heading"><h2>运行评测</h2><span>已选{selected.length}例 · {selected.length * repeats}次真实制作</span></div><div className="eval-launch-fields"><label>评测名称<input value={name} maxLength={100} onChange={e => setName(e.target.value)} placeholder="例如：新版动效回归"/></label><label>文本模型<select value={modelId} onChange={e => setModelId(e.target.value)}><option value="">当前默认模型</option>{models.filter(m => m.kind === 'text' && m.enabled && m.hasApiKey).map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>每例重复<select value={repeats} onChange={e => setRepeats(+e.target.value)}><option value={1}>1 次</option><option value={2}>2 次</option><option value={3}>3 次</option></select></label><button className="admin-save" disabled={busy || active || !selected.length || Boolean(missing)} onClick={() => void start()}><Play size={16}/>{active ? '已有评测执行中' : '开始评测'}</button></div><p className="eval-muted">按顺序调用现有 Agent、模型和渲染工具。每轮保存用例、素材哈希、模型、代码和 skill 指纹。{missing ? `「${missing.name}」须先绑定至少${missing.expectation.minSources}段素材。` : '最终是否通过还取决于成片审查，生成文件本身不等于质量通过。'}</p></section>
      <div className="eval-case-toolbar"><div className="eval-filters">{(['all','hot-news','knowledge','multi-video'] as const).map(value => <button key={value} className={category === value ? 'active' : ''} onClick={() => setCategory(value)}>{value === 'all' ? '全部' : categoryNames[value]}</button>)}</div><div className="eval-inline"><button className="eval-secondary" onClick={() => setSelected(current => [...new Set([...current, ...visibleCases.filter(c => c.enabled).map(c => c.id)])])}>选择本组</button><button className="eval-secondary" onClick={() => setSelected([])}>清空选择</button><button className="eval-secondary" onClick={() => setEditor(blankCase())}><Plus size={15}/>新增用例</button></div></div>
      <div className="eval-case-grid">{visibleCases.map(test => <article className={`admin-panel eval-case ${selected.includes(test.id) ? 'selected' : ''}`} key={test.id}><div className="eval-case-title"><label><input aria-label={`选择${test.name}`} type="checkbox" checked={selected.includes(test.id)} disabled={!test.enabled} onChange={e => setSelected(current => e.target.checked ? [...current, test.id] : current.filter(id => id !== test.id))}/><strong>{test.name}</strong></label><button aria-label={`配置${test.name}`} onClick={() => setEditor(test)}><Settings2 size={17}/></button></div><p>{test.description}</p><div className="eval-tags"><span>{categoryNames[test.category]}</span><span>{test.expectation.seconds}秒 · {test.expectation.format}</span><span>{test.messages.length}轮指令</span><span>{test.enabled ? `v${test.version} · ≥${test.threshold}分` : '已停用'}</span></div><details><summary>查看指令与验收要求</summary><ol>{test.messages.map((m,i) => <li key={i}>{m}</li>)}</ol><p>字幕{test.expectation.captions ? '必须' : '不限'} · HTML{test.expectation.html ? '必须' : '不限'} · {test.expectation.minSources ? `至少使用${test.expectation.minSources}段原素材 · 已绑定${test.fixtureIds.length}段` : '无需源视频'}{test.expectation.requiredWords.length ? ` · 必须说到：${test.expectation.requiredWords.join('、')}` : ''}</p></details>{test.fixtureIds.length < test.expectation.minSources ? <small className="eval-needs-fixture">待绑定评测视频</small> : null}</article>)}</div>
      <section className="admin-panel eval-fixtures"><div className="admin-panel-heading"><h2>独立评测素材</h2><label className="eval-secondary eval-upload"><Upload size={15}/>{busy ? '处理中…' : '上传评测视频'}<input aria-label="上传评测视频" type="file" accept="video/*" multiple disabled={busy} onChange={event => void upload(event)}/></label></div><p className="eval-muted">每段最多100 MB，每次最多6段；用于多个视频的剪辑指令。普通用户的素材不会自动进入评测集。</p>{fixtures.length ? <div className="eval-fixture-list">{fixtures.map(f => <article key={f.id}><Film size={18}/><div><strong>{f.name}</strong><small>{f.duration.toFixed(1)}秒 · {(f.bytes/1024/1024).toFixed(1)} MB · {f.hasAudio ? '有音轨' : '无音轨'} · SHA {f.sha256.slice(0,10)}</small></div></article>)}</div> : <p className="eval-empty">还没有评测视频。上传后为剪辑用例绑定至少两段素材。</p>}</section>
    </> : <>
      <div className="eval-history-toolbar"><label>评测记录<select aria-label="选择评测记录" value={runId} onChange={e => { setRun(null); setRunId(e.target.value); setResultId(''); setBaselineId(''); }}><option value="">选择一轮评测</option>{runs.map(r => <option key={r.id} value={r.id}>{r.name} · {new Date(r.createdAt).toLocaleString('zh-CN')} · {runStatusName(r.status)}</option>)}</select></label>{run ? <><label>对比基线<select aria-label="对比基线" value={baselineId} onChange={e => setBaselineId(e.target.value)}><option value="">不对比</option>{runs.filter(r => r.id !== runId).map(r => <option key={r.id} value={r.id}>{r.name} · {new Date(r.createdAt).toLocaleString('zh-CN')}</option>)}</select></label><button className="eval-secondary" onClick={() => void downloadReport()}><Download size={15}/>导出本轮记录</button>{['running','stopping'].includes(run.status) ? <button className="eval-secondary" disabled={busy || run.status === 'stopping'} onClick={() => void stop()}><Square size={14}/>{run.status === 'stopping' ? '正在停止…' : '停止评测'}</button> : null}</> : null}</div>
      {!run ? <div className="admin-panel eval-empty"><BarChart3 size={28}/><p>从评测集选择用例并开始，或选择已有评测记录。</p></div> : <>
        <div className="eval-stats"><article><small>生成完成率</small><strong>{((summary?.completionRate || 0)*100).toFixed(0)}%</strong><span>{summary?.rendered || 0}/{run.results.length} 有成片</span></article><article><small>质量通过率</small><strong>{((summary?.passRate || 0)*100).toFixed(0)}%</strong><span>{summary?.passed || 0}/{run.results.length} 通过</span></article><article><small>自动评测均分</small><strong>{summary?.averageScore ?? '—'}</strong><span>未生成、停止的用例不混入均分</span></article><article><small>评测进度</small><strong>{summary?.finished || 0}/{run.results.length}</strong><span>{['running','stopping'].includes(run.status) ? '后台执行中' : '本轮已结束'}</span></article></div>
        <p className="eval-muted">代码 {run.snapshot.revision?.slice(0,7) || '无Git版本'} / {run.snapshot.implementationHash.slice(0,10)} · skill {run.snapshot.skillHash.slice(0,10)} · {run.snapshot.rubricVersion} · {run.snapshot.models.map(m => `${m.kind}: ${m.modelId}`).join(' · ')}</p>
        {summary ? <div className="eval-category-summary">{summary.categories.filter(c => c.total).map(c => <span key={c.category}>{categoryNames[c.category]}：{c.passed}/{c.total}通过 · 均分{c.averageScore ?? '—'}</span>)}</div> : null}
        {baseline ? <p className="eval-muted">{baseline.snapshot.rubricVersion !== run.snapshot.rubricVersion ? '两轮评分规则不同，不计算分数差值。' : '仅比较指令、预期、阈值及素材哈希一致的用例；实时热点的具体新闻与日期可能变化。'}人工分数单独保留。</p> : null}
        <div className="eval-table-wrap admin-panel"><table className="eval-table"><thead><tr><th>用例</th><th>状态 / 当前步骤</th><th>自动分数</th>{baseline ? <th>与基线差值</th> : null}<th>耗时</th><th>查看</th></tr></thead><tbody>{run.results.map(r => { const scores = baselineScores.get(r.caseHash), delta = r.score !== undefined && scores?.length ? Math.round((r.score - scores.reduce((a,b) => a+b,0)/scores.length)*10)/10 : null; return <tr key={r.id}><td><strong>{r.case.name}</strong><small>{categoryNames[r.case.category]} · 第{r.repeat}次</small></td><td><span className={`eval-status ${r.status}`}>{statusName(r)}</span>{r.status === 'running' ? <small>{r.stage === 'queued' ? '等待执行' : r.stage === 'running' ? '执行中' : r.stage}{r.progress !== undefined ? ` · ${r.progress}%` : ''}</small> : r.error ? <small>{r.error}</small> : null}</td><td>{r.score ?? '—'}{r.humanReview ? <small>人工{r.humanReview.score}</small> : null}</td>{baseline ? <td>{delta === null ? '不可比' : `${delta > 0 ? '+' : ''}${delta}`}</td> : null}<td>{r.elapsedMs ? `${(r.elapsedMs/1000).toFixed(0)}秒` : '—'}</td><td><button className="eval-secondary" aria-label={`查看${r.case.name}第${r.repeat}次结果`} onClick={() => setResultId(r.id)}>详情</button></td></tr>; })}</tbody></table></div>
        {result ? <ResultDetail key={result.id} result={result} runId={run.id} token={token} refresh={() => refresh()}/> : null}
      </>}
    </>}
    {editor ? <CaseEditor key={`${editor.id}-${editor.version}`} test={editor} fixtures={fixtures} close={() => setEditor(null)} save={save}/> : null}
  </div>;
}
