// Public marketing assets. Generated by scripts/publish-product-video.mjs.
export const productVideo = {
  "title": "96 秒了解轻剪",
  "durationSeconds": 96,
  "width": 1920,
  "height": 1080,
  "fps": 30,
  "publishedAt": "2026-10-01T09:13:55.684Z",
  "assets": {
    "video": {
      "url": "https://qingjian-shikanon-media-sg-2026.oss-ap-southeast-1.aliyuncs.com/qingjian/marketing/launch/8666c6cb4d057d20/qingjian-launch-1080p.mp4",
      "bytes": 49184995,
      "sha256": "8666c6cb4d057d209c369dfda43f84597a52e32bdedc95c099be98ad8eb4ba96",
      "contentType": "video/mp4"
    },
    "poster": {
      "url": "https://qingjian-shikanon-media-sg-2026.oss-ap-southeast-1.aliyuncs.com/qingjian/marketing/launch/7770c0e30a914ab4/qingjian-launch-poster.jpg",
      "bytes": 46160,
      "sha256": "7770c0e30a914ab48f358f981c13aa99cd7eed3e96bff038cfb4b2083a869d67",
      "contentType": "image/jpeg"
    },
    "project": {
      "url": "https://qingjian-shikanon-media-sg-2026.oss-ap-southeast-1.aliyuncs.com/qingjian/marketing/launch/e5083824c36c9697/qingjian-launch-editable.zip",
      "bytes": 28282450,
      "sha256": "e5083824c36c9697d0ec3bb7bdc7f8fa33ea1b6f7a0b601a06dc4c37d8116794",
      "contentType": "application/zip"
    }
  }
} as const;
